name: Security Audit

on:
  schedule:
    # Runs every Sunday at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked

      - name: Run security audit
        # To ignore a specific advisory, add `--ignore RUSTSEC-ID`
        run: cargo audit