name: Security Audit

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    # Runs every Sunday at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo-audit
        uses: actions/cache@v4
        id: cache-cargo-audit
        with:
          path: ~/.cargo/bin/cargo-audit
          key: ${{ runner.os }}-cargo-audit

      - name: Install cargo-audit
        if: steps.cache-cargo-audit.outputs.cache-hit != 'true'
        run: cargo install cargo-audit --locked

      - name: Run security audit
        # To ignore a specific advisory, add `--ignore RUSTSEC-ID`
        run: cargo audit